-- =============================================================
-- Instance seed: the reference data every new instance needs on
-- day one.
--
-- Applied by `npm run provision` (the seed-data step) against a
-- freshly migrated project, and safe to rerun against an existing
-- one to pick up additions.
--
-- READ supabase/seed/README.md BEFORE ADDING ANYTHING HERE.
-- The short version: reference data changes belong in this file as
-- part of the feature that needs them, never as a direct insert
-- into a live database. New instances are born from this file, so
-- anything added straight to production is silently missing from
-- every instance provisioned afterwards.
--
-- Every statement is idempotent — ON CONFLICT on a real unique
-- constraint, the same pattern the Phase 1 seed scripts use.
--
-- WHAT IS DELIBERATELY NOT HERE
--
--   * Company data of any kind. Companies, profiles, commitments,
--     priorities, meetings, scorecards. A new instance starts empty
--     and its first company is created through the app.
--   * User accounts. The instance's first admin is created by the
--     provisioning step that follows, from the --admin-email flag.
--   * The public.instances registry row. That row is what makes a
--     hostname resolve, so it is written last, to the CONTROL PLANE,
--     by its own step — deliberately not here. Every project has an
--     instances table because the migrations create one; only the
--     control plane's copy is ever read.
--   * Classroom, entirely. Categories, lessons and trainings are
--     authored in the product on the primary instance and delivered
--     by `npm run sync:content`. This file used to insert a "Phase 1"
--     category as structure-not-content; that is now removed. See
--     "One dataset, one owner" below.
--
-- WHAT IS ALREADY HANDLED ELSEWHERE
--
--   * strengths_items (38 rows) ships in migration
--     0103_strengths_items_seed.sql and therefore arrives with
--     `supabase db push`. It is reference data, but it is already
--     versioned as a migration and duplicating it here would give
--     two sources of truth.
--   * The practices registry is code, not data:
--     src/lib/practices/registry.ts. Nothing to seed.
--   * A new company's default leadership functions are created when
--     the company is created (see createCompanyAction), not per
--     instance.
--
-- ONE DATASET, ONE OWNER
--
-- Every dataset is owned by exactly one tool: this seed, or
-- scripts/sync-content.ts. Never both.
--
-- Classroom was briefly owned by both, and the overlap was not
-- harmless. This file inserted its category with no explicit id, so
-- every instance minted its own UUID for the same logical row. Sync
-- matches by primary key, so it saw production's category and the
-- instance's category as different rows and planned an insert plus a
-- delete — with both holding the unique slug "build-the-team", which
-- is a constraint violation waiting on the write order. Worse, the
-- two tools would have fought forever: every `--seed` run would
-- re-mint a divergent row for the next sync to delete.
--
-- The rule is therefore about ownership, not about ordering. Two
-- tools writing the same table cannot be made safe by running them
-- in the right sequence, because there is no sequence in which both
-- are authoritative.
--
-- If a dataset belongs here: it is fixed reference data that ships
-- with the code and is identical on every instance. If it belongs to
-- sync: it is authored in the product on the primary. Content that
-- is authored anywhere else belongs to neither and should not be
-- propagated at all.
-- =============================================================

-- ---- No statements ------------------------------------------
--
-- Deliberately. Everything a new instance needs today arrives
-- either through a migration (strengths_items, via 0103) or through
-- content sync (Classroom). This file is kept rather than deleted
-- because it is where the next piece of genuine reference data goes,
-- and because the provisioning step that runs it is part of the
-- proven path.
